# Generated by Django 3.2.18 on 2023-03-23 18:54

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='title',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(default=2, verbose_name=builtins.min),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='name',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
