# Generated by Django 3.2.18 on 2023-03-24 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20230324_0846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='qty',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='measure',
            new_name='measurement_unit',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='title',
            new_name='name',
        ),
    ]
